### ISSUE TITLE
"Andlib format is not supported anymore, use aar instead"

### ISSUE THREAD

**Issue by Stians92** [littlemonkeyltd/QRScanner#2]
Codename One's build servers used ant up until last week. They have now upgraded the build system to use gradle, and I am now receiving an error message when trying to build my project with your cn1lib:

> Exception: java.lang.Exception: andlib format is not supported anymore, use aar instead
> com.codename1.build.daemon.AndroidGradleBuilder.build(AndroidGradleBuilder.java:235)
> com.codename1.build.daemon.AndroidBuilder.build(AndroidBuilder.java:151)
> com.codename1.build.daemon.Executor$5.run(Executor.java:789)

**Comment by DigNZ** [comment]
Will take a look at this.

**Comment by gardner** [comment]
I am getting this using the new gradle build system on Codename One. There's no indication of which files are causing the problem. Did you ever resolve this? What is this related to?
