### ISSUE TITLE
App crash on android 6.0

### ISSUE THREAD

**Issue by kyri33** [littlemonkeyltd/QRScanner#6]
With the new android 6.0, SDK 23, there are new permissions. This causes the app to crash when the Scanner attempts to open the camera. It does not seem to request permission to use the camera, thus causing the crash.

**Comment by kyri33** [comment]
Could be this? https://github.com/dm77/barcodescanner/issues/123

**Comment by kyri33** [comment]
Could the solution be here? https://github.com/dm77/barcodescanner/blob/master/zbar-sample/src/main/java/me/dm7/barcodescanner/zbar/sample/MainActivity.java

Look in the launchActivity method. They check for permissions first and request them. I think this needs to be added in the android native code of this library. Before startActivityForResult is called.

**Comment by kyri33** [comment]
I believe this is the problem: https://github.com/dm77/barcodescanner/issues/123

**Comment by NickoftheSouth** [comment]
This should be fixed in the code I've just merged in. 
I've also added a new release with an updated cn1lib file.
It was indeed related to a bug in the central lib we were using (ZBar).
